# Generated by Django 5.2.9 on 2026-02-26 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrialConfig',
            fields=[
                ('id', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('trial_days', models.PositiveIntegerField(default=30)),
            ],
        ),
    ]
