# Generated by Django 5.2.9 on 2026-04-06 13:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_verification_token',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='email_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='InstitutionProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('job_title', models.CharField(max_length=255)),
                ('work_email', models.EmailField(max_length=254)),
                ('institution_name', models.CharField(max_length=255)),
                ('institution_type', models.CharField(choices=[('university', 'University'), ('polytechnic', 'Polytechnic'), ('secondary_school', 'Secondary School'), ('training_org', 'Training Organization'), ('professional_institute', 'Professional Institute'), ('tutorial_center', 'Tutorial Center')], max_length=50)),
                ('position', models.CharField(choices=[('president', 'President/Rector'), ('vice_chancellor', 'Vice Chancellor/Principal'), ('provost', 'Provost'), ('dean', 'Dean'), ('hod', 'Head of Department (HOD)'), ('teaching_staff', 'Teaching Staff'), ('it_admin', 'IT/Admin Staff'), ('others', 'Others')], max_length=50)),
                ('department', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('purpose', models.TextField(help_text='Comma-separated purposes selected during registration')),
                ('can_create_diploma_courses', models.BooleanField(default=False)),
                ('can_create_degree_programs', models.BooleanField(default=False)),
                ('can_upload_projects', models.BooleanField(default=False)),
                ('allowed_certifications', models.TextField(default='completion', help_text='Comma-separated list of allowed certification types')),
                ('dashboard_variant', models.CharField(default='tutorial', help_text='Determines which dashboard template to use', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='institution_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Institution Profile',
                'verbose_name_plural': 'Institution Profiles',
            },
        ),
    ]
