# Generated by Django 5.2.9 on 2026-04-15 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='material',
            options={'ordering': ['-created_at'], 'permissions': [('can_manage_materials', 'Can create, edit, delete materials')]},
        ),
        migrations.RenameIndex(
            model_name='material',
            new_name='materials_m_is_publ_579f59_idx',
            old_name='materials_m_is_publ_idx',
        ),
        migrations.RenameIndex(
            model_name='material',
            new_name='materials_m_topic_c_4b98ec_idx',
            old_name='materials_m_topic_c_idx',
        ),
        migrations.RenameIndex(
            model_name='material',
            new_name='materials_m_area_4ffa65_idx',
            old_name='materials_m_area_idx',
        ),
        migrations.RenameIndex(
            model_name='materialdownload',
            new_name='materials_m_user_id_0a1c17_idx',
            old_name='materials_m_user_id_created_idx',
        ),
        migrations.RenameIndex(
            model_name='materialdownload',
            new_name='materials_m_downloa_bb55cd_idx',
            old_name='materials_m_download_token_idx',
        ),
        migrations.RenameIndex(
            model_name='materialpurchase',
            new_name='materials_m_user_id_eb2ad2_idx',
            old_name='materials_m_user_id_accessed_idx',
        ),
        migrations.RenameIndex(
            model_name='materialpurchase',
            new_name='materials_m_materia_d86ce1_idx',
            old_name='materials_m_material_accessed_idx',
        ),
    ]
