# Generated by Django 5.2.9 on 2026-04-15 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0002_alter_material_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='image_name',
            field=models.CharField(blank=True, help_text='Original image filename', max_length=255),
        ),
        migrations.AddField(
            model_name='material',
            name='image_url',
            field=models.URLField(blank=True, help_text='Optional thumbnail/cover image URL for the material', null=True),
        ),
    ]
