# Generated by Django 5.2.9 on 2026-02-14 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blogcomment_author_name_alter_blogcomment_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='image_description',
            field=models.CharField(blank=True, help_text='Alt text and description for the featured image', max_length=255),
        ),
    ]
