# Generated by Django 5.2.9 on 2026-07-26 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_blogcategory_blog_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogAd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('badge_text', models.CharField(blank=True, help_text='e.g. FREE DOWNLOAD or FEATURED COURSE', max_length=50)),
                ('bullets', models.TextField(blank=True, help_text='Comma-separated bullet points (e.g. Python, SQL, Power BI)')),
                ('button_text', models.CharField(default='Download Free', max_length=50)),
                ('button_link', models.CharField(max_length=512)),
                ('image', models.CharField(blank=True, max_length=512)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='blog',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='blog',
            name='is_popular',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='blog',
            name='is_trending',
            field=models.BooleanField(default=False),
        ),
    ]
