# Generated by Django 4.2.11 on 2025-12-25 15:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_manage_users', models.BooleanField(default=False)),
                ('can_manage_institutions', models.BooleanField(default=False)),
                ('can_manage_courses', models.BooleanField(default=False)),
                ('can_manage_cbt', models.BooleanField(default=False)),
                ('can_view_payments', models.BooleanField(default=False)),
                ('can_manage_blog', models.BooleanField(default=False)),
                ('can_manage_subadmins', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_subadmins', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subadmin_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sub-Admin',
                'verbose_name_plural': 'Sub-Admins',
            },
        ),
    ]
