# Generated by Django 5.2.9 on 2026-01-09 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subadmin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subadmin',
            name='can_view_messages',
            field=models.BooleanField(default=False),
        ),
    ]
