# Generated by Django 5.2.9 on 2026-04-21 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subadmin', '0002_add_json_permissions'),
        ('subadmin', '0002_subadmin_can_view_messages'),
    ]

    operations = [
    ]
