# Generated by Django 5.2.9 on 2026-04-09 16:08

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MockExamQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('question_image', models.URLField(blank=True, help_text='URL to question image/diagram', null=True)),
                ('question_type', models.CharField(choices=[('multiple_choice', 'Multiple Choice'), ('true_false', 'True/False'), ('fill_blank', 'Fill in the Blank'), ('short_answer', 'Short Answer'), ('essay', 'Essay'), ('matching', 'Matching'), ('ordering', 'Ordering')], default='multiple_choice', max_length=50)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=20)),
                ('marks', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('negative_marks', models.IntegerField(default=0, help_text='Penalty for wrong answer', validators=[django.core.validators.MinValueValidator(0)])),
                ('explanation', models.TextField(blank=True, help_text='Explanation shown after exam')),
                ('explanation_image', models.URLField(blank=True, null=True)),
                ('order', models.IntegerField(default=0)),
                ('is_mandatory', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Mock Exam Question',
                'verbose_name_plural': 'Mock Exam Questions',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CustomMockExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('instructions', models.TextField(blank=True, help_text='Exam instructions shown to students')),
                ('total_duration_minutes', models.IntegerField(default=120, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(480)])),
                ('total_marks', models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(1)])),
                ('passing_marks', models.IntegerField(default=50, validators=[django.core.validators.MinValueValidator(0)])),
                ('difficulty_level', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard'), ('mixed', 'Mixed')], default='medium', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('is_published', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_streaming', models.BooleanField(default=False, help_text='True if exam is streamed from external platform')),
                ('external_exam_id', models.CharField(blank=True, help_text='ID of exam on external platform', max_length=255, null=True)),
                ('external_exam_url', models.URLField(blank=True, help_text='URL to stream exam from external platform', max_length=500, null=True)),
                ('subject_area', models.CharField(blank=True, help_text='e.g., JAMB Biology, WAEC Mathematics', max_length=255)),
                ('exam_year', models.IntegerField(blank=True, help_text='Year the exam is from/for', null=True)),
                ('language', models.CharField(default='English', max_length=50)),
                ('total_attempts', models.IntegerField(default=0)),
                ('avg_score', models.DecimalField(decimal_places=2, default=0, help_text='Average score of all attempts', max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_mock_exams', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Custom Mock Exam',
                'verbose_name_plural': 'Custom Mock Exams',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MockExamAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('time_spent_seconds', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('submitted', 'Submitted'), ('completed', 'Completed'), ('abandoned', 'Abandoned')], default='in_progress', max_length=20)),
                ('is_submitted', models.BooleanField(default=False)),
                ('total_marks', models.IntegerField(default=0)),
                ('obtained_marks', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('grade', models.CharField(blank=True, help_text='A, B, C, D, F, etc.', max_length=2)),
                ('passed', models.BooleanField(default=False)),
                ('device_type', models.CharField(blank=True, help_text='Desktop, Mobile, Tablet', max_length=50)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mock_exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='mock_exams.custommockexam')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mock_exam_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mock Exam Attempt',
                'verbose_name_plural': 'Mock Exam Attempts',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='MockExamExternalPlatform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_name', models.CharField(max_length=255, unique=True)),
                ('platform_type', models.CharField(choices=[('jamb', 'JAMB'), ('waec', 'WAEC'), ('neco', 'NECO'), ('custom_api', 'Custom API'), ('iframe', 'iFrame Embed')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('platform_url', models.URLField(max_length=500)),
                ('api_key', models.CharField(blank=True, help_text='API key for authentication', max_length=500)),
                ('api_secret', models.CharField(blank=True, help_text='API secret for authentication', max_length=500)),
                ('api_endpoint', models.URLField(blank=True, help_text='API endpoint URL', max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('sync_enabled', models.BooleanField(default=False, help_text='Allow syncing exams from this platform')),
                ('last_sync_time', models.DateTimeField(blank=True, null=True)),
                ('webhook_url', models.URLField(blank=True, help_text='Webhook URL for platform notifications', max_length=500)),
                ('auth_headers', models.JSONField(default=dict, help_text='Custom headers for API requests')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Mock Exam External Platform',
                'verbose_name_plural': 'Mock Exam External Platforms',
                'ordering': ['platform_name'],
                'indexes': [models.Index(fields=['is_active'], name='mock_exams__is_acti_f49506_idx')],
            },
        ),
        migrations.AddField(
            model_name='custommockexam',
            name='external_platform',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mock_exams', to='mock_exams.mockexamexternalplatform'),
        ),
        migrations.CreateModel(
            name='MockExamFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee_amount', models.DecimalField(decimal_places=2, default=0, help_text='0 = Free exam', max_digits=10)),
                ('currency', models.CharField(default='NGN', max_length=3)),
                ('discount_percentage', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('promo_code', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mock_exam', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fee', to='mock_exams.custommockexam')),
            ],
            options={
                'verbose_name': 'Mock Exam Fee',
                'verbose_name_plural': 'Mock Exam Fees',
            },
        ),
        migrations.CreateModel(
            name='MockExamOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_text', models.TextField()),
                ('option_image', models.URLField(blank=True, help_text='URL to option image/diagram', null=True)),
                ('option_letter', models.CharField(default='A', help_text='A, B, C, D, E, etc.', max_length=2)),
                ('is_correct', models.BooleanField(default=False)),
                ('explanation', models.TextField(blank=True)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='mock_exams.mockexamquestion')),
            ],
            options={
                'verbose_name': 'Mock Exam Option',
                'verbose_name_plural': 'Mock Exam Options',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MockExamResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_answer_text', models.TextField(blank=True, help_text='For essay/short answer questions')),
                ('is_correct', models.BooleanField(default=False)),
                ('marks_obtained', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('time_spent_seconds', models.IntegerField(default=0)),
                ('attempted', models.BooleanField(default=False, help_text='Whether student attempted or skipped this question')),
                ('marked_for_review', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='mock_exams.mockexamattempt')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mock_exams.mockexamquestion')),
                ('selected_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mock_exams.mockexamoption')),
            ],
            options={
                'verbose_name': 'Mock Exam Result',
                'verbose_name_plural': 'Mock Exam Results',
                'ordering': ['question__order'],
            },
        ),
        migrations.CreateModel(
            name='MockExamSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('subject_icon', models.URLField(blank=True, help_text='URL to subject icon/image', null=True)),
                ('num_questions', models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(200)])),
                ('time_allocation_minutes', models.IntegerField(default=20, validators=[django.core.validators.MinValueValidator(1)])),
                ('marks_per_question', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('order', models.IntegerField(default=0, help_text='Display order in exam')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mock_exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='mock_exams.custommockexam')),
            ],
            options={
                'verbose_name': 'Mock Exam Subject',
                'verbose_name_plural': 'Mock Exam Subjects',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='mockexamquestion',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='mock_exams.mockexamsubject'),
        ),
        migrations.CreateModel(
            name='MockExamActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create_exam', 'Create Exam'), ('update_exam', 'Update Exam'), ('delete_exam', 'Delete Exam'), ('publish_exam', 'Publish Exam'), ('archive_exam', 'Archive Exam'), ('add_subject', 'Add Subject'), ('update_subject', 'Update Subject'), ('delete_subject', 'Delete Subject'), ('add_question', 'Add Question'), ('update_question', 'Update Question'), ('delete_question', 'Delete Question'), ('set_fee', 'Set Fee'), ('update_fee', 'Update Fee'), ('configure_platform', 'Configure External Platform'), ('sync_platform', 'Sync Platform Exams')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('change_details', models.JSONField(default=dict, help_text='Detailed changes made')),
                ('affected_students', models.IntegerField(default=0, help_text='Number of students affected by this action')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mock_exam_activities', to=settings.AUTH_USER_MODEL)),
                ('mock_exam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='mock_exams.custommockexam')),
            ],
            options={
                'verbose_name': 'Mock Exam Activity Log',
                'verbose_name_plural': 'Mock Exam Activity Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['admin', '-created_at'], name='mock_exams__admin_i_de3257_idx'), models.Index(fields=['mock_exam', '-created_at'], name='mock_exams__mock_ex_deb91f_idx'), models.Index(fields=['action'], name='mock_exams__action_fe0419_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='mockexamattempt',
            index=models.Index(fields=['user', '-start_time'], name='mock_exams__user_id_9da713_idx'),
        ),
        migrations.AddIndex(
            model_name='mockexamattempt',
            index=models.Index(fields=['mock_exam', '-start_time'], name='mock_exams__mock_ex_a091a1_idx'),
        ),
        migrations.AddIndex(
            model_name='mockexamattempt',
            index=models.Index(fields=['status'], name='mock_exams__status_9b321b_idx'),
        ),
        migrations.AddIndex(
            model_name='custommockexam',
            index=models.Index(fields=['admin', '-created_at'], name='mock_exams__admin_i_85ccbb_idx'),
        ),
        migrations.AddIndex(
            model_name='custommockexam',
            index=models.Index(fields=['is_published', '-created_at'], name='mock_exams__is_publ_8855c7_idx'),
        ),
        migrations.AddIndex(
            model_name='custommockexam',
            index=models.Index(fields=['external_platform'], name='mock_exams__externa_92ea7e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='mockexamoption',
            unique_together={('question', 'option_letter')},
        ),
        migrations.AddIndex(
            model_name='mockexamresult',
            index=models.Index(fields=['attempt', 'question'], name='mock_exams__attempt_95c954_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='mockexamresult',
            unique_together={('attempt', 'question')},
        ),
        migrations.AddIndex(
            model_name='mockexamsubject',
            index=models.Index(fields=['mock_exam', 'order'], name='mock_exams__mock_ex_62f822_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='mockexamsubject',
            unique_together={('mock_exam', 'subject_name')},
        ),
        migrations.AddIndex(
            model_name='mockexamquestion',
            index=models.Index(fields=['subject', 'order'], name='mock_exams__subject_027f63_idx'),
        ),
        migrations.AddIndex(
            model_name='mockexamquestion',
            index=models.Index(fields=['difficulty'], name='mock_exams__difficu_5cb0b3_idx'),
        ),
    ]
