# Generated by Django 5.2.9 on 2026-04-14 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mock_exams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mockexamquestion',
            name='question_type',
            field=models.CharField(choices=[('multiple_choice', 'Multiple Choice'), ('radio', 'Radio Button'), ('checkbox', 'Checkboxes'), ('true_false', 'True/False'), ('fill_blank', 'Fill in the Blank'), ('short_answer', 'Short Answer'), ('essay', 'Essay'), ('matching', 'Matching'), ('ordering', 'Ordering')], default='multiple_choice', max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='mockexamoption',
            unique_together={('question', 'order')},
        ),
    ]
