# Generated by Django 5.2.9 on 2026-04-14 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mock_exams', '0002_alter_mockexamquestion_question_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mockexamquestion',
            name='option_counter',
            field=models.IntegerField(default=0, help_text='Next option order index for this question'),
        ),
    ]
