# Generated by Django 5.2.9 on 2026-04-14 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mock_exams', '0003_mockexamquestion_option_counter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mockexamoption',
            name='option_image',
            field=models.ImageField(blank=True, help_text='Option image/diagram', null=True, upload_to='mock_exams/options/'),
        ),
        migrations.AlterField(
            model_name='mockexamquestion',
            name='explanation_image',
            field=models.ImageField(blank=True, null=True, upload_to='mock_exams/explanations/'),
        ),
        migrations.AlterField(
            model_name='mockexamquestion',
            name='question_image',
            field=models.ImageField(blank=True, help_text='Question image/diagram', null=True, upload_to='mock_exams/questions/'),
        ),
    ]
