# Generated by Django 4.2.11 on 2025-12-26 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_diploma_portfolio_portfoliogalleryitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='theme_color',
            field=models.CharField(blank=True, default='', help_text='Hex color for portfolio theming', max_length=7),
        ),
    ]
