# Generated by Django 5.2.9 on 2025-12-26 14:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_portfolio_theme_color'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='creator_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Amount to course/diploma creator', max_digits=10),
        ),
        migrations.AddField(
            model_name='payment',
            name='diploma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='courses.diploma'),
        ),
        migrations.AddField(
            model_name='payment',
            name='paystack_reference',
            field=models.CharField(blank=True, help_text='Paystack reference code', max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='verified_at',
            field=models.DateTimeField(blank=True, help_text='When Paystack verified the payment', null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='kind',
            field=models.CharField(choices=[('course', 'Course Purchase'), ('diploma', 'Diploma Enrollment'), ('unlock', 'Account Unlock')], default='course', max_length=20),
        ),
        migrations.CreateModel(
            name='PaystackSubAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_code', models.CharField(help_text='Bank code from Paystack', max_length=10)),
                ('account_number', models.CharField(max_length=20)),
                ('account_name', models.CharField(max_length=255)),
                ('subaccount_code', models.CharField(blank=True, help_text='Paystack subaccount_code', max_length=100, null=True, unique=True)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='paystack_subaccount', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Paystack Sub-accounts',
            },
        ),
    ]
