# Generated by Django 5.2.9 on 2025-12-26 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_payment_creator_amount_payment_diploma_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
