# Generated by Django 5.2.9 on 2026-01-05 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_certificate'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='certificate',
            new_name='courses_cer_user_id_6a53cf_idx',
            old_name='courses_cert_user_id_idx',
        ),
        migrations.RenameIndex(
            model_name='certificate',
            new_name='courses_cer_certifi_a9a7a7_idx',
            old_name='courses_cert_cert_id_idx',
        ),
    ]
