# Generated by Django 5.2.9 on 2026-01-05 21:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_rename_courses_cert_user_id_idx_courses_cer_user_id_6a53cf_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='flutterwave_reference',
            field=models.CharField(blank=True, help_text='Flutterwave tx_ref code', max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='flutterwave_transaction_id',
            field=models.CharField(blank=True, help_text='Flutterwave transaction ID', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_provider',
            field=models.CharField(choices=[('paystack', 'Paystack'), ('flutterwave', 'Flutterwave')], default='paystack', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='verified_at',
            field=models.DateTimeField(blank=True, help_text='When payment was verified', null=True),
        ),
        migrations.CreateModel(
            name='FlutterwaveSubAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_code', models.CharField(help_text='Bank code from Flutterwave', max_length=10)),
                ('account_number', models.CharField(max_length=20)),
                ('account_name', models.CharField(max_length=255)),
                ('subaccount_id', models.CharField(blank=True, help_text='Flutterwave subaccount_id', max_length=100, null=True, unique=True)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='flutterwave_subaccount', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Flutterwave Sub-accounts',
            },
        ),
    ]
