# Generated by Django 5.2.9 on 2026-01-09 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_lesson_duration_minutes_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='signature_image',
            field=models.CharField(blank=True, help_text='URL to the uploaded signature image', max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='institution',
            name='signer_name',
            field=models.CharField(blank=True, help_text='Name of the person signing certificates (e.g. Dr. John Doe)', max_length=255, null=True),
        ),
    ]
