# Generated by Django 5.2.9 on 2026-01-09 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0017_institution_signature_image_institution_signer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='signer_position',
            field=models.CharField(blank=True, help_text='Job title (e.g. Dean of Studies, Registrar)', max_length=255, null=True),
        ),
    ]
