# Generated by Django 5.2.9 on 2026-01-14 09:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0018_institution_signer_position'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivationFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('exam', 'Exam (global)'), ('interview', 'Interview Subject')], default='exam', max_length=20)),
                ('exam_identifier', models.CharField(blank=True, help_text='Exam id or slug for which this fee applies', max_length=255, null=True)),
                ('subject_id', models.IntegerField(blank=True, help_text='Subject id (for interview subjects)', null=True)),
                ('currency', models.CharField(default='NGN', max_length=8)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activation_fee_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ActivationUnlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_identifier', models.CharField(blank=True, help_text='Exam id or slug', max_length=255, null=True)),
                ('subject_id', models.IntegerField(blank=True, null=True)),
                ('activated_at', models.DateTimeField(auto_now_add=True)),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activations', to='courses.payment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'exam_identifier', 'subject_id')},
            },
        ),
    ]
