# Generated by Django 5.2.9 on 2026-01-17 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0019_activationfee_activationunlock'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='webhook_attempts',
            field=models.IntegerField(default=0, help_text='Number of times webhook was received for this payment'),
        ),
        migrations.AddField(
            model_name='payment',
            name='webhook_received',
            field=models.BooleanField(default=False, help_text='Whether webhook confirmation received from gateway'),
        ),
        migrations.AddField(
            model_name='payment',
            name='webhook_received_at',
            field=models.DateTimeField(blank=True, help_text='When webhook was received from gateway', null=True),
        ),
    ]
