# Generated by Django 5.2.9 on 2026-01-17 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0020_payment_webhook_attempts_payment_webhook_received_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='gateway_fee',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Fee charged by payment gateway (Paystack/Flutterwave)', max_digits=10),
        ),
        migrations.AddField(
            model_name='payment',
            name='net_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Amount received after gateway fee', max_digits=10),
        ),
    ]
