# Generated by Django 5.2.9 on 2026-01-17 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0021_payment_gateway_fee_payment_net_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='GospelVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtube_url', models.URLField(help_text='YouTube video URL', max_length=512)),
                ('scheduled_time', models.TimeField(help_text='Time of day (HH:MM) when video should pop up on user dashboards')),
                ('title', models.CharField(blank=True, default='Gospel Message', max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
