# Generated by Django 5.2.9 on 2026-01-22 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0022_gospelvideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='recipient_code',
            field=models.CharField(blank=True, help_text='Paystack recipient code for tutor sub-account', max_length=255, null=True),
        ),
    ]
