# Generated by Django 5.2.9 on 2026-02-04 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0024_paymentsplitconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='currency',
            field=models.CharField(default='NGN', help_text='ISO 4217 currency code (e.g., NGN, USD)', max_length=3),
        ),
    ]
