# Generated by Django 5.2.9 on 2026-02-06 14:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0025_payment_currency'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_type',
            field=models.CharField(choices=[('beginner', 'Beginner Course'), ('intermediate', 'Intermediate Course'), ('advanced', 'Advanced Course'), ('master', 'Master Course'), ('specialized', 'Specialized Course'), ('certification', 'Certification Program'), ('bootcamp', 'Bootcamp'), ('workshop', 'Workshop'), ('other', 'Other')], default='other', help_text='Type/badge for course listing', max_length=50),
        ),
        migrations.AddField(
            model_name='course',
            name='level',
            field=models.CharField(blank=True, default='Beginner', help_text='Course difficulty level', max_length=50),
        ),
        migrations.AddField(
            model_name='course',
            name='outcome',
            field=models.TextField(blank=True, help_text='What students will learn'),
        ),
        migrations.AddField(
            model_name='course',
            name='required_tools',
            field=models.TextField(blank=True, help_text='Tools/software required'),
        ),
        migrations.CreateModel(
            name='ModuleQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Module Quiz', max_length=255)),
                ('description', models.TextField(blank=True)),
                ('passing_score', models.PositiveIntegerField(default=70, help_text='Minimum percentage score to pass (0-100)')),
                ('is_required', models.BooleanField(default=True, help_text='Must student pass this quiz to proceed to next module?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module', models.OneToOneField(help_text='Each module can have one quiz', on_delete=django.db.models.deletion.CASCADE, related_name='quiz', to='courses.module')),
            ],
            options={
                'verbose_name': 'Module Quiz',
                'verbose_name_plural': 'Module Quizzes',
            },
        ),
        migrations.CreateModel(
            name='ModuleQuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('score', models.PositiveIntegerField(blank=True, help_text='Score achieved (0-100 percentage)', null=True)),
                ('total_points', models.PositiveIntegerField(default=0)),
                ('earned_points', models.PositiveIntegerField(default=0)),
                ('passed', models.BooleanField(default=False)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='courses.modulequiz')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Module Quiz Attempt',
                'unique_together': {('user', 'quiz')},
            },
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Question text/prompt')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order within quiz')),
                ('points', models.PositiveIntegerField(default=1, help_text='Points awarded for correct answer')),
                ('explanation', models.TextField(blank=True, help_text='Explanation shown after answering')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='courses.modulequiz')),
            ],
            options={
                'verbose_name': 'Quiz Question',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='QuizOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(help_text='Option text', max_length=500)),
                ('is_correct', models.BooleanField(default=False, help_text='Is this the correct answer?')),
                ('order', models.PositiveIntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='courses.quizquestion')),
            ],
            options={
                'verbose_name': 'Quiz Option',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='QuizAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField(default=False)),
                ('points_earned', models.PositiveIntegerField(default=0)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='courses.modulequizattempt')),
                ('selected_option', models.ForeignKey(blank=True, help_text='The option the student selected', null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.quizoption')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.quizquestion')),
            ],
            options={
                'unique_together': {('attempt', 'question')},
            },
        ),
    ]
