# Generated by Django 5.2.9 on 2026-02-06 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0026_course_course_type_course_level_course_outcome_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activationfee',
            name='account_role',
            field=models.CharField(blank=True, choices=[('tutor', 'Tutor'), ('institution', 'Institution')], help_text='Role this account activation fee applies to', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='activationfee',
            name='type',
            field=models.CharField(choices=[('exam', 'Exam (global)'), ('interview', 'Interview Subject'), ('account', 'Account Activation')], default='exam', max_length=20),
        ),
    ]
