# Generated by Django 5.2.9 on 2026-02-09 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0028_visit_alter_diploma_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='visit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='courses.visit'),
        ),
        migrations.AddField(
            model_name='visit',
            name='city',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='country',
            field=models.CharField(blank=True, db_index=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='is_exit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='visit',
            name='is_landing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='visit',
            name='region',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='session_id',
            field=models.CharField(blank=True, db_index=True, max_length=128, null=True),
        ),
    ]
