# Generated by Django 5.2.9 on 2026-02-09 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0029_payment_visit_visit_city_visit_country_visit_is_exit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visit',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='course',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
