# Generated by Django 5.2.9 on 2026-02-12 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0031_remove_course_updated_at_visit_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='logo_image',
            field=models.CharField(blank=True, help_text='URL to the uploaded institution logo', max_length=512, null=True),
        ),
    ]
