# Generated by Django 5.2.9 on 2026-02-22 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0032_institution_logo_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='promo_code',
            field=models.CharField(blank=True, help_text='Promo code applied to this payment', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='promo_discount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Discount amount applied from promo', max_digits=10),
        ),
    ]
