# Generated by Django 5.2.9 on 2026-03-25 15:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0033_payment_promo_code_payment_promo_discount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='courses_published_before_verification',
            field=models.BooleanField(default=False, help_text='Whether courses can be seen in marketplace before verification'),
        ),
        migrations.AddField(
            model_name='institution',
            name='custom_share_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Custom share percentage for this institution (e.g., 85.00 for 85%). Overrides platform default.', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='institution',
            name='email',
            field=models.EmailField(blank=True, help_text='Institution contact email', max_length=254),
        ),
        migrations.AddField(
            model_name='institution',
            name='phone',
            field=models.CharField(blank=True, help_text='Institution contact phone number', max_length=20),
        ),
        migrations.AddField(
            model_name='institution',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Reason for rejection if status is rejected'),
        ),
        migrations.AddField(
            model_name='institution',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'Pending Verification'), ('approved', 'Verified & Approved'), ('rejected', 'Verification Rejected')], default='pending', help_text='Verification status of the institution', max_length=20),
        ),
        migrations.AddField(
            model_name='institution',
            name='verified_at',
            field=models.DateTimeField(blank=True, help_text='When institution was verified', null=True),
        ),
        migrations.AddField(
            model_name='institution',
            name='verified_by',
            field=models.ForeignKey(blank=True, help_text='Admin who verified this institution', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_institutions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='LegalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('terms_of_service', 'Terms of Service'), ('creator_agreement', 'Creator Agreement'), ('data_privacy', 'Data Privacy Policy'), ('intellectual_property', 'Intellectual Property Agreement'), ('payment_terms', 'Payment Terms & Conditions'), ('code_of_conduct', 'Code of Conduct'), ('other', 'Other')], max_length=50, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('document_file', models.CharField(help_text='URL to the PDF/document file', max_length=512)),
                ('version', models.CharField(default='1.0', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Legal Document',
                'verbose_name_plural': 'Legal Documents',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='TutorVerificationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('id_card', 'National ID / Passport'), ('qualification', 'Educational Qualification'), ('teaching_certificate', 'Teaching Certificate'), ('experience_proof', 'Experience Reference'), ('address_proof', 'Address Proof'), ('other', 'Other Document')], max_length=50)),
                ('document_file', models.CharField(help_text='URL to uploaded document (PDF, image, etc.)', max_length=512)),
                ('document_name', models.CharField(help_text='Original filename', max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True, help_text='Admin notes on the document')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_tutor_documents', to=settings.AUTH_USER_MODEL)),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tutor Verification Document',
                'verbose_name_plural': 'Tutor Verification Documents',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='VerificationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('business_registration', 'Business Registration Document'), ('tax_id', 'Tax ID/Certificate'), ('ownership_certificate', 'Ownership Certificate'), ('accreditation', 'Accreditation Certificate'), ('establishment_proof', 'Proof of Establishment'), ('director_id', 'Director/Owner ID'), ('address_proof', 'Address Proof'), ('other', 'Other Document')], max_length=50)),
                ('document_file', models.CharField(help_text='URL to uploaded document (PDF, image, etc.)', max_length=512)),
                ('document_name', models.CharField(help_text='Original filename', max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True, help_text='Admin notes on the document')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_documents', to='courses.institution')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Verification Document',
                'verbose_name_plural': 'Verification Documents',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
