# Generated by Django 5.2.9 on 2026-04-01 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_compliance_submission'),
        ('courses', '0034_institution_courses_published_before_verification_and_more'),
    ]

    operations = [
    ]
