# Generated by Django 5.2.9 on 2026-04-01 13:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0035_merge_20260401_1435'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorverificationdocument',
            name='submission',
            field=models.ForeignKey(blank=True, help_text='Compliance submission folder this document belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tutor_documents', to='courses.compliancesubmission'),
        ),
        migrations.AlterField(
            model_name='verificationdocument',
            name='submission',
            field=models.ForeignKey(blank=True, help_text='Compliance submission folder this document belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='institution_documents', to='courses.compliancesubmission'),
        ),
        migrations.AlterUniqueTogether(
            name='compliancesubmission',
            unique_together={('entity_type', 'tutor', 'submitted_at')},
        ),
    ]
