# Generated by Django 5.2.9 on 2026-04-06 12:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0036_alter_tutorverificationdocument_submission_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='legaldocument',
            name='institution_recipients',
            field=models.ManyToManyField(blank=True, help_text='Institutions who should receive this document', related_name='legal_documents_assigned', to='courses.institution'),
        ),
        migrations.AddField(
            model_name='legaldocument',
            name='recipient_type',
            field=models.CharField(choices=[('all', 'All Users'), ('specific', 'Specific Recipients')], default='all', help_text='Whether to send to all users or specific recipients', max_length=20),
        ),
        migrations.AddField(
            model_name='legaldocument',
            name='sent_at',
            field=models.DateTimeField(blank=True, help_text='When this document was assigned to specific recipients', null=True),
        ),
        migrations.AddField(
            model_name='legaldocument',
            name='tutor_recipients',
            field=models.ManyToManyField(blank=True, help_text='Tutors who should receive this document', related_name='legal_documents_assigned_as_tutor', to=settings.AUTH_USER_MODEL),
        ),
    ]
