# Generated by Django 5.2.9 on 2026-04-08 08:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbt', '0008_examattempt_test_name_studentanswer_subject'),
        ('courses', '0037_legaldocument_institution_recipients_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='activationunlock',
            unique_together={('user', 'exam_identifier')},
        ),
        migrations.AddField(
            model_name='activationunlock',
            name='selected_exam_subjects',
            field=models.ManyToManyField(blank=True, help_text='Selected subjects for CBT exam (max 4)', related_name='student_unlocks', to='cbt.subject'),
        ),
        migrations.AlterField(
            model_name='activationunlock',
            name='subject_id',
            field=models.IntegerField(blank=True, help_text='Legacy field for interview subject unlocks', null=True),
        ),
        migrations.AddIndex(
            model_name='activationunlock',
            index=models.Index(fields=['user', 'exam_identifier'], name='courses_act_user_id_343c5d_idx'),
        ),
        migrations.AddIndex(
            model_name='activationunlock',
            index=models.Index(fields=['user', 'subject_id'], name='courses_act_user_id_29e758_idx'),
        ),
    ]
