# Generated by Django 5.2.9 on 2026-04-15 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0038_alter_activationunlock_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='kind',
            field=models.CharField(choices=[('course', 'Course Purchase'), ('diploma', 'Diploma Enrollment'), ('unlock', 'Account Unlock'), ('material', 'Material Purchase')], default='course', max_length=20),
        ),
    ]
