# Generated by Django 5.2.9 on 2026-04-19 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbt', '0008_examattempt_test_name_studentanswer_subject'),
        ('courses', '0039_alter_payment_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='diploma',
            name='academics',
            field=models.TextField(blank=True, help_text='Curriculum and course structure'),
        ),
        migrations.AddField(
            model_name='diploma',
            name='admissions',
            field=models.TextField(blank=True, help_text='Admission requirements and how to apply'),
        ),
        migrations.AddField(
            model_name='diploma',
            name='careers',
            field=models.TextField(blank=True, help_text='Career readiness and job prospects'),
        ),
        migrations.AddField(
            model_name='diploma',
            name='overview',
            field=models.TextField(blank=True, help_text='Program overview and introduction'),
        ),
        migrations.AddField(
            model_name='diploma',
            name='student_experience',
            field=models.TextField(blank=True, help_text='Student testimonials and learning experience'),
        ),
        migrations.AddField(
            model_name='diploma',
            name='tuition_financing',
            field=models.TextField(blank=True, help_text='Fees breakdown and payment options'),
        ),
        migrations.AlterField(
            model_name='activationunlock',
            name='selected_exam_subjects',
            field=models.ManyToManyField(blank=True, help_text='Selected subjects for CBT exam (max 5)', related_name='student_unlocks', to='cbt.subject'),
        ),
    ]
