# Generated by Django 5.2.9 on 2026-04-19 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0040_diploma_academics_diploma_admissions_diploma_careers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diploma',
            name='academics',
            field=models.TextField(blank=True, help_text='Academic details and curriculum'),
        ),
        migrations.AlterField(
            model_name='diploma',
            name='admissions',
            field=models.TextField(blank=True, help_text='Admissions information and requirements'),
        ),
        migrations.AlterField(
            model_name='diploma',
            name='careers',
            field=models.TextField(blank=True, help_text='Career prospects and alumni success'),
        ),
        migrations.AlterField(
            model_name='diploma',
            name='overview',
            field=models.TextField(blank=True, help_text='Overview of the diploma program'),
        ),
        migrations.AlterField(
            model_name='diploma',
            name='student_experience',
            field=models.TextField(blank=True, help_text='Student experience and testimonials'),
        ),
        migrations.AlterField(
            model_name='diploma',
            name='tuition_financing',
            field=models.TextField(blank=True, help_text='Tuition fees and financing options'),
        ),
    ]
