# Generated by Django 5.2.9 on 2026-05-11 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0042_referral_system'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='referralevent',
            new_name='courses_ref_referre_12a58f_idx',
            old_name='courses_ref_referr_8df17b_idx',
        ),
        migrations.RenameIndex(
            model_name='referralevent',
            new_name='courses_ref_event_t_2c024e_idx',
            old_name='courses_ref_event_t_d04064_idx',
        ),
        migrations.RenameIndex(
            model_name='referralevent',
            new_name='courses_ref_referre_adf89c_idx',
            old_name='courses_ref_referre_f9aef1_idx',
        ),
        migrations.RenameIndex(
            model_name='referralrelationship',
            new_name='courses_ref_referre_f04f50_idx',
            old_name='courses_ref_referr_55c4a6_idx',
        ),
        migrations.RenameIndex(
            model_name='referralrelationship',
            new_name='courses_ref_code_us_6bf423_idx',
            old_name='courses_ref_code_us_8d5b42_idx',
        ),
    ]
