# Generated by Django 5.2.9 on 2026-05-11 16:38

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0043_rename_courses_ref_referr_8df17b_idx_courses_ref_referre_12a58f_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='referralsettings',
            name='referral_percent',
            field=models.DecimalField(decimal_places=6, default=Decimal('0.05'), help_text='Decimal fraction representing percent of platform share to award (e.g., 0.05 means 5%)', max_digits=8),
        ),
        migrations.AlterField(
            model_name='referralevent',
            name='points',
            field=models.DecimalField(decimal_places=2, help_text='Positive for awards, negative for redemptions', max_digits=12),
        ),
        migrations.AlterField(
            model_name='referralprofile',
            name='points_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
    ]
