# Generated by Django 5.2.9 on 2026-05-23 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0044_referralsettings_referral_percent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legaldocument',
            name='document_type',
            field=models.CharField(choices=[('terms_of_service', 'Terms of Service'), ('creator_agreement', 'Creator Agreement'), ('data_privacy', 'Data Privacy Policy'), ('intellectual_property', 'Intellectual Property Agreement'), ('payment_terms', 'Payment Terms & Conditions'), ('code_of_conduct', 'Code of Conduct'), ('other', 'Other')], max_length=50),
        ),
    ]
