# Generated by Django 5.2.9 on 2026-06-20 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0045_alter_legaldocument_document_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='views_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of times the course detail has been viewed'),
        ),
    ]
