# Generated by Django 5.2.9 on 2026-07-22 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0046_course_views_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_series',
            field=models.BooleanField(default=False, help_text='Designates this course as an umbrella Series course'),
        ),
        migrations.CreateModel(
            name='SeriesItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_series', to='courses.course')),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series_items', to='courses.course')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('series', 'course')},
            },
        ),
    ]
