# Generated by Django 5.2.9 on 2026-08-20 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0048_proplan_usersubscription_subscriptionresetlog_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='usersubscription',
            new_name='courses_use_user_id_194ac9_idx',
            old_name='courses_use_user_id_44f123_idx',
        ),
        migrations.RenameIndex(
            model_name='usersubscription',
            new_name='courses_use_end_dat_ddce85_idx',
            old_name='courses_use_end_dat_88b901_idx',
        ),
    ]
