# Generated by Django 5.2.9 on 2026-08-20 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0049_rename_courses_use_user_id_44f123_idx_courses_use_user_id_194ac9_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proplan',
            name='material_download_limit',
            field=models.PositiveIntegerField(default=0, help_text='0 for unlimited, or specific max downloads allowed per billing cycle'),
        ),
        migrations.AlterField(
            model_name='proplan',
            name='allow_materials_download',
            field=models.BooleanField(default=True, help_text='Grants download of past questions & study materials'),
        ),
    ]
