# Generated by Django 5.2.9 on 2025-12-26 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='message',
            new_name='messaging_m_recipie_3abcda_idx',
            old_name='messaging_m_recipie_idx',
        ),
        migrations.RenameIndex(
            model_name='message',
            new_name='messaging_m_sender__9b0bb2_idx',
            old_name='messaging_m_sender_idx',
        ),
    ]
