# Generated by Django 5.2.9 on 2026-04-20 13:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_rename_messaging_m_recipie_idx_messaging_m_recipie_3abcda_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thread_id', models.CharField(db_index=True, help_text="Unique identifier for conversation thread (e.g., 'admin_{sender_id}_{recipient_id}')", max_length=255)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direct_messages_received', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direct_messages_sent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['thread_id', 'created_at'], name='messaging_d_thread__c93b89_idx'), models.Index(fields=['recipient', '-created_at'], name='messaging_d_recipie_0c08d2_idx'), models.Index(fields=['sender', '-created_at'], name='messaging_d_sender__8190f9_idx'), models.Index(fields=['is_read'], name='messaging_d_is_read_608081_idx')],
            },
        ),
    ]
