# Generated by Django 5.2.9 on 2025-12-11 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbt', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='year',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
