# Generated by Django 5.2.9 on 2026-01-10 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbt', '0005_alter_examattempt_options_examattempt_is_submitted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='cbt_questions/'),
        ),
    ]
