# Generated by Django 5.2.9 on 2026-04-06 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbt', '0007_question_explanation'),
    ]

    operations = [
        migrations.AddField(
            model_name='examattempt',
            name='test_name',
            field=models.CharField(blank=True, help_text='Custom name for multi-subject exams', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='subject',
            field=models.ForeignKey(blank=True, help_text='Subject of the question - auto-populated from question', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_answers', to='cbt.subject'),
        ),
    ]
