# Generated by Django 5.2.9 on 2026-04-20 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbt', '0008_examattempt_test_name_studentanswer_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='examattempt',
            name='is_trial_attempt',
            field=models.BooleanField(default=False, help_text='Whether this is a free trial attempt (max 5 per exam)'),
        ),
    ]
