# Generated by Django 5.2.9 on 2026-08-10 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbt', '0009_add_trial_attempt_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='free_trial_attempts',
            field=models.PositiveIntegerField(default=5, help_text='Number of free trial attempts allowed per student for this exam'),
        ),
        migrations.AddField(
            model_name='exam',
            name='free_trial_questions_per_subject',
            field=models.PositiveIntegerField(default=20, help_text='Max questions per subject in free trial mode (0 = no limit)'),
        ),
    ]
