# Generated by Django 5.2.9 on 2026-08-14 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbt', '0010_exam_free_trial_attempts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='subject_select_limit',
            field=models.PositiveIntegerField(default=0, help_text='Number of subjects a user can select during registration. 0 means they unlock all subjects (no selection).'),
        ),
    ]
