# Generated by Django 5.2.9 on 2026-04-20 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessoncontent',
            name='meta_description',
            field=models.CharField(blank=True, help_text='SEO meta description (60-160 chars), displayed in search results', max_length=160),
        ),
        migrations.AddField(
            model_name='lessoncontent',
            name='meta_keywords',
            field=models.CharField(blank=True, help_text='Comma-separated keywords for SEO', max_length=255),
        ),
        migrations.AddField(
            model_name='lessoncontent',
            name='og_image',
            field=models.URLField(blank=True, default='', help_text='Open Graph image URL for social sharing'),
        ),
        migrations.AddField(
            model_name='lessoncontent',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL-friendly identifier for SEO', max_length=255, unique=True),
        ),
    ]
