# Generated by Django 5.2.9 on 2026-05-02 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0003_lesson_subfolders_and_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['subject', 'subfolder', 'order', 'name']},
        ),
    ]
